name: personajes_marvel_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  dio: 5.8.0+1
  fpdart: 1.1.1
  flutter_dotenv: 5.2.1
  crypto: 3.0.6
  flutter_spinkit: 5.2.1
  infinite_scroll_pagination: 4.1.0
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
